//#define DOS 1
//#define IN_VNIIAS 1//флаг выполнения отладки
//#define KANALS 1 //Признак включения в программу теста каналов обмена
//#define lex_lex 1 //Признак выполнения конвертации текстов сообщений
//#define MOUSE_NASTR 1              C^\Documents and Settings\Volnov M P\Hf,jxbq cnjk\TEST_TUMS/lnk@
//#define NALAD 1
#define OTLADKA 0//флаг отладочного режима для контроля каналов
//#define SETKA 1//Признак  включения на  экране  сетки координат на  переднем  плане
//#define SETKA1  1//Признак  включения на  экране  сетки координат на  заднем  плане
#define TELEUPR 1 //флаг подключения к датчикам режима управления
#define WORK  1 //флаг включения рабочего режима (для отладки - 0)
//#define DEMONSTR 1
